app/base/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
import debug_toolbar
from django.conf.urls.static import static

from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^login/$', auth_views.LoginView.as_view(), name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(next_page='home'), name='logout'),

    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^issues/', include('issues.urls')),

    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/issues/urls.py
from django.conf.urls import url
from issues import views

urlpatterns = [
    url(r'^$', views.IssueList.as_view(), name='issues_list'),
    url(r'^new/?$', views.IssueCreate.as_view(), name='issues_new'),
    url(r'^(?P<pk>[0-9]+)/update/?$', views.IssueUpdate.as_view(), name='issues_update'),
    url(r'^(?P<pk>[0-9]+)/delete/?$', views.IssueDelete.as_view(), name='issues_delete'),
]

app/issues/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.text import Truncator


class Category(models.Model):
    name = models.CharField(max_length=40)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Issue(models.Model):
    STATES = (
        ('N', 'New'),
        ('A', 'Active'),
        ('S', 'Solved')
    )

    state = models.CharField(max_length=1, default='N', choices=STATES)
    description = models.TextField()
    created_ts = models.DateTimeField('Creation date', auto_now_add=True)
    solved_ts = models.DateTimeField('Solved date', null=True, blank=True)

    author = models.ForeignKey(User, related_name='issue_author')
    category = models.ForeignKey(Category)
    solver = models.ForeignKey(User, blank=True, null=True, related_name='issue_solver')

    class Meta:
        ordering = ["created_ts"]

    def clean(self):
        if self.state == "S" and not self.solver:
            raise ValidationError("When Issue is Solver it needs to have assigned an User which Solved the issue!")

    def __str__(self):
        return Truncator(self.description).chars(30)

    def get_absolute_url(self):
        return

app/issues/views.py
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Avg, F, Max, Min
from django.urls import reverse_lazy
from django.views.generic import ListView, DeleteView, UpdateView, CreateView
from issues.models import Issue


class SuperUserOnlyMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_superuser


class IssueList(LoginRequiredMixin, ListView):
    model = Issue
    context_object_name = 'issues'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['stats'] = {
            "avg": Issue.objects.filter(state="S").aggregate(val=Avg(F('solved_ts') - F('created_ts'))),
            "min": Issue.objects.filter(state="S").aggregate(val=Min(F('solved_ts') - F('created_ts'))),
            "max": Issue.objects.filter(state="S").aggregate(val=Max(F('solved_ts') - F('created_ts'))),
        }

        return context


class IssueCreate(SuperUserOnlyMixin, CreateView):
    model = Issue
    fields = ['description', 'category']
    success_url = reverse_lazy('issues_list')
    template_name_suffix = '_create_form'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class IssueUpdate(SuperUserOnlyMixin, UpdateView):
    model = Issue
    success_url = reverse_lazy('issues_list')
    fields = ['description', 'category', 'state', 'solver']
    template_name_suffix = '_update_form'

    def form_valid(self, form):
        if form.initial['state'] != form.cleaned_data['state']:
            if form.cleaned_data['state'] == 'S':
                form.instance.solved_ts = datetime.now()
            else:
                form.instance.solved_ts = None

        return super().form_valid(form)


class IssueDelete(SuperUserOnlyMixin, DeleteView):
    model = Issue
    success_url = reverse_lazy('issues_list')

app/issues/templates/issues/issue_confirm_delete.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% load i18n %}

{% block title %}{% trans 'Delete issue' %}{% endblock %}

{% block content %}


    <form method="post" class="form">
        {% csrf_token %}

        <div class="text-center text-danger">
            {% trans 'Are you really sure you want to delete the issue?' %}<br><br>

            <button type="submit" class="btn btn-danger">
                {% bootstrap_icon "star" %} {% trans 'Yes' %}
            </button>
        <a href="{% url 'issues_list' %}" class="btn btn-default">{% trans 'Cancel' %}</a>
        </div>
    </form>
{% endblock %}

app/issues/templates/issues/issue_create_form.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% load i18n %}

{% block title %}{% trans 'New issue' %}{% endblock %}

{% block content %}
    <h2>{% trans 'New issue' %}</h2>

    {% bootstrap_messages %}

    <form method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                {% bootstrap_icon "star" %} {% trans 'Create new issue' %}
            </button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'issues_list' %}"/>
    </form>
{% endblock %}

app/issues/templates/issues/issue_list.html
{% extends "base.html" %}

{% block title %}List of Issues{% endblock %}

{% block content %}
    <h2>Issues</h2>

    <h3>Statistics</h3>

    <ul>
    <li><strong>Average solving time:</strong> {{ stats.avg.val }}</li>
    <li><strong>Minimum solving time:</strong> {{ stats.min.val }}</li>
    <li><strong>Maximum solving time:</strong> {{ stats.max.val }}</li>
    </ul>

    <table class="table">
        <thead>
        <tr>
            <th>Created date</th>
            <th>Solved date</th>
            <th>Category</th>
            <th>State</th>
            <th>Description</th>
            <th>Solver</th>
            <th></th>
        </tr>
        </thead>
        <tbody class="table-hover">
        {% for issue in issues %}
            <tr>
                <td>{{ issue.created_ts|date:"H:m d.n.Y" }}</td>
                <td>{{ issue.solved_ts|date:"H:m d.n.Y"}}</td>
                <td>{{ issue.category }}</td>
                <td>{{ issue.get_state_display }}</td>
                <td>{{ issue.description }}</td>
                <td>{{ issue.solver }}</td>
                <td>
                    {% if user.is_superuser %}
                        <a href="{% url 'issues_update' pk=issue.id %}">Edit</a> |
                        <a href="{% url 'issues_delete' pk=issue.id %}">Delete</a>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

app/issues/templates/issues/issue_update_form.html
{% extends "base.html" %}

{% load bootstrap3 %}
{% load i18n %}

{% block title %}{% trans 'Update issue' %}{% endblock %}

{% block content %}
    <h2>{% trans 'Update issue' %}</h2>

    {% bootstrap_messages %}

    <form method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button type="submit" class="btn btn-primary">
                {% bootstrap_icon "star" %} {% trans 'Update issue' %}
            </button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'issues_list' %}"/>
    </form>
{% endblock %}

app/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

app/templates/base.html
{% load i18n %}
{% load static %}

{% get_current_language as LANGUAGE_CODE %}
{% get_available_languages as LANGUAGES %}
{% get_language_info_list for LANGUAGES as languages %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="robots" content="ALL,FOLLOW">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="{% static 'main.css' %}">

    <link rel="stylesheet" type="text/css"
          href="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css"/>
    <script src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js"></script>
    <script>
        window.addEventListener("load", function () {
            window.cookieconsent.initialise({
                "palette": {
                    "popup": {
                        "background": "#000"
                    },
                    "button": {
                        "background": "#f1d600"
                    }
                }
            })
        });
    </script>
</head>
<body>
<div class="container">
    {% block menu %}
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#nav_collapse" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'home' %}">U_Issues</a>
                </div>

                <div class="collapse navbar-collapse" id="nav_collapse">
                    <ul class="nav navbar-nav">
                        {% if user.is_authenticated %}

                            <li {% if request.resolver_match.url_name == 'issues_list' %}class="active"{% endif %}><a
                                    href="{% url 'issues_list' %}">{% trans 'List of issues' %}</a></li>
                        {% endif %}
                        {% if user.is_superuser %}
                            <li {% if request.resolver_match.url_name == 'issues_new' %}class="active"{% endif %}><a
                                    href="{% url 'issues_new' %}">{% trans 'New issue' %}</a></li>
                        {% endif %}
                    </ul>

                    {% if user.is_authenticated %}
                        <a href="{% url 'logout' %}"
                           class="btn btn-default navbar-btn navbar-right mr10">{% trans 'Log out' %}</a>

                        {% if user.is_superuser %}
                            <a href="{% url 'admin:index' %}"
                               class="btn btn-default navbar-btn navbar-right mr10">{% trans 'Administration' %}</a>
                        {% endif %}

                        <p class="navbar-text navbar-right mr10">Signed in as <strong>{{ user.username }}</strong></p>
                    {% else %}
                        <a href="{% url 'login' %}"
                           class="btn btn-default navbar-btn navbar-right">{% trans 'Log in' %}</a>
                    {% endif %}
                </div>


            </div>
        </nav>
    {% endblock %}

    <div class="content {% block content_class %}{% endblock %}">
        {% block content %}{% endblock %}

    </div>
</div>

{% block javascript %}
    <script type="text/javascript" src="{% static 'lib.js' %}"></script>
    <script type="text/javascript" src="{% static 'main.js' %}"></script>
{% endblock %}
</body>
</html>

app/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1 class="text-center">Welcome!</h1>

    <div class="text-center">
        <h4>Welcome to brand new, disruptive and exciting U_Issues tracker!</h4>

    It offers very innovative and breakthrough concepts which will ensure that your products will
    stay bug-free and that you will deliver the top-quality product!

    <h3>And guess what?! It is for free!</h3>
    </div>
{% endblock content %}